### ISSUE TITLE
User reported issue: unable to 'submit' if no strings are modified from Java/Flash translation

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#127]
Currently, if we already have a translation for the Java/Flash version of a sim and a translator opens the HTML5 version of that sim, they can only 'submit' if they add/modify a string. A translator has reported that he would like to maintain the Java/Flash translation, but cannot due to this restriction.

**Comment by ariel-phet** [comment]
@oliver-phet as a workaround, the translator could probably submit with a minor alteration, and then resubmit the corrected version, but we should obviously look into this.

**Comment by jbphet** [comment]
We no longer provide partial translations of HTML sims that were derived from Java or Flash sims.  A while back we decided that this wasn't a great approach, since we were ending up with a number of partially translated versions each time we published a new sim with these ported Java/Flash strings in place, so instead we are now expecting translators to start from scratch when a new HTML sim is published.  So far this hasn't proven to be a problem.  That means that this GitHub issue is no longer relevant, so I'm closing it.
