### ISSUE TITLE
Translation Utility missing Java strings for Atomic Interactions

### ISSUE THREAD

**Issue by arouinfar** [phetsims/rosetta#138]
@jbphet When translating Atomic Interactions into the fa locale, the Java strings were not pre-populated in the translation utility (common strings were still present). Sándor also encountered this issue for the hu locale, as reported in https://github.com/phetsims/atomic-interactions/issues/65.

**Comment by jbphet** [comment]
The Java versions of the States of Matter simulations were created many years ago, and the way that we name our string identifiers has changed radically since then.  As a result, none of the string keys in the Java versions of the string files overlap with those in the current English strings for the HTML5 simulation.  It would take a fair amount of work to fix this up, so I decided to just leave the files empty and have the translators start from scratch.

Assigning back to @arouinfar.  @arouinfar - If you have a strong objection to this decision, please add @ariel-phet to to the dialog and we can discuss, otherwise please close.

**Comment by arouinfar** [comment]
@jbphet It's only a minor inconvenience to re-enter previously translated strings, so I don't with its worth addressing.
