### ISSUE TITLE
set up the logs to be longer and withstand a restart

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#143]
I was recently trying to figure out if Rosetta had been restarted to resolve a question about whether it had been updated.  The log only contained ~7 days worth of data, from Nov 23 through Nov 30.  I discussed this with @mattpen, and he said that this may indicate that the process was restarted.  If true, that's a problem, because we will never be able to look at the log output just before a crash and restart.  However, I feel like I've seen restart messages in the log before.  The bottom line is that we need logs that survive a restart and that keep more than 7 days worth of data.

Assigning to @mattpen, he can pass this along to someone else if needed.

**Comment by mattpen** [comment]
@jbphet - It looks like we may have log messages for rosetta going back a month.

If you run `grep phet-server\ rosetta /var/log/messages* | less` you can see logs going back to Oct 31.

This command parses through 4-5 files which may not be grepped in specific order so the dates may make odd jumps in that output.  

It looks like these are rotated weekly and kept in storage for a month.  If you'd like to adjust those settings, please let me know.

**Comment by jbphet** [comment]
I looked the logs and determined that there wasn't a restart of rosetta, so I think they are totally time based.

A month of logs seems a little short.  Can we make it three months without consuming too much disk space?

Also, the grep approach is a little klunky since data can be out of order.  Is it hard to configure it so that, say, a month's worth of data is actually available in the journalctl log?

**Comment by mattpen** [comment]
@phetsims/mark-morlino Can you help us adjust the logging for rosetta and build-server in journalctl on phet-server?

The logs from the past 7 days are currently available in journalctl.  `/var/log/messages` is storing the logs as well, rotating files weekly and retaining files for 1 month.  Is it possible to keep 3 months worth of files?  Can we configure journalctl to have access to read 3 months as well, perhaps by keeping messages in persistent storage rather than in memory?

**Comment by markmorlino** [comment]
@mattpen 
I think the easiest way to determine when any service last started is probably to use the ps command and look at the date/time.

```
ps aux |grep rosetta
phet-ad+ 126795  0.0  0.0 1257300 70696 ?       Ssl  Oct24   0:30 /usr/bin/node /data/share/phet/phet-repos/rosetta/rosetta.js
```

A restart of a service shouldn't clear anything from the journalctl journal for that service, or from /var/log/messages. Journalctl will attempt to dynamically adjust its retention period based on available disk space. It does this across everything it keeps logs for, so spam from one service could potentially cause a reduction in the retention period for everything. In my opinion journalctl should not be relied upon as a source for archival/historic logs. It forwards messages to syslog and that's usually the easiest place to manage and view them once you get past wanting to see recent entries. I think it would be possibly to force it to use /var instead of /run and then force a retention period of 3 months but I don't think it is configurable on a per-service basis. It is currently using 4.1gb of space under /run/log/journal to store 7 days. So, using journalctl to store 3 months would require at least 50gb of space and possibly much more. We just have the one datapoint so we don't know what is typical for 1 week or what the min/max amounts might be for a week's worth of logs.

The out-of order problem is pretty easily addressed by passing the log files to grep in the correct order. The entries inside each of the messages files will always be in chronological order, so as long as you give grep the file list in the order you want, everything will be displayed in order from oldest to newest.
`grep phet-server\ rosetta /var/log/messages-* /var/log/messages | less`
or
`grep phet-server\ rosetta $(ls -rt /var/log/messages*) | less`

The retention of /var/log/messages was set to 4 weeks and I just changed it to 12. These files are relatively small so I don't think we need to worry about increasing the capacity of /var to hold the extra logs.

**Comment by mattpen** [comment]
@jbphet - It looks like we have 3 months of logs that will be available (although obviously logs prior to November 2016 won't be available), and a method to parse them in chronological order.  Will this method work for you?  It looks like configuring it through journalctl would not be ideal.

**Comment by jbphet** [comment]
Works for me, thanks.  Closing.
