### ISSUE TITLE
Add support for country-specific versions of the English language locale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#149]
Add support for country-specific versions of the English language locale, e.g. en_CA and en_GB. (Confirm that those are correct locales.)

This was motivated by https://github.com/phetsims/unit-rates/issues/198.  According to @jbphet, this may "create unanticipated side effects".  Presumably he's anticipating that something may be assuming that there is only one 'en' locale.

Consult with @ariel-phet on priority.

**Comment by jbphet** [comment]
Adding @ariel-phet to list of assignees in order to set priority.  We're building up some "technical debt" on translation, would be good to tackle a few of these issues.

Here's a time and risk estimate in order to help with prioritization.  If things go well, I think I could add the new locales and verify them through some test builds in about three hours.  However, I'm concerned that some portions of our build code may not handle other English locales very well, and tracking down and fixing issues like this could take some time.  I scanned through the code for occurrences of 'en', and everything I saw looked pretty reasonable, so I think the risk of problems is reasonably low, but certainly non-zero.

**Comment by ariel-phet** [comment]
@jbphet considering the low risk, and that we have already had user requests, I am labeling high priority. Please dedicate one day next week to translation issues, and lets see where we are at after that day.

**Comment by jbphet** [comment]
I just searched for a list of English locale codes, and below is what I found on a site called "Locale Planet", see http://www.localeplanet.com/icu/iso639.html#en.

```
English (en)
English (American Samoa) (en-AS)
English (Australia) (en-AU)
English (Barbados) (en-BB)
English (Belgium) (en-BE)
English (Bermuda) (en-BM)
English (Botswana) (en-BW)
English (Belize) (en-BZ)
English (Canada) (en-CA)
English (United Kingdom) (en-GB)
English (Guam) (en-GU)
English (Guyana) (en-GY)
English (Hong Kong SAR China) (en-HK)
English (Ireland) (en-IE)
English (India) (en-IN)
English (Jamaica) (en-JM)
English (Marshall Islands) (en-MH)
English (Northern Mariana Islands) (en-MP)
English (Malta) (en-MT)
English (Mauritius) (en-MU)
English (Namibia) (en-NA)
English (New Zealand) (en-NZ)
English (Philippines) (en-PH)
English (Pakistan) (en-PK)
English (Singapore) (en-SG)
English (Trinidad and Tobago) (en-TT)
English (U.S. Minor Outlying Islands) (en-UM)
English (United States) (en-US)
English (United States, Computer) (en-US-POSIX)
English (U.S. Virgin Islands) (en-VI)
English (South Africa) (en-ZA)
English (Zimbabwe) (en-ZW)
```

Adding all of these would definitely be overkill, so my plan is to add en-GB (United Kingdom, a.k.a. Great Britain) and en-CA (Canada).  My reasoning is that Canada uses the metric system but uses the same dollar sign as the US for currency, so this would work well for the immediate need of creating a metric version Unit Rates.  The United Kingdom is being added for more general reasons, such as if someone wants to change some words to more British spellings, e.g. Colour Vision.  It would also support using the British pound symbol (£) for the currency indicator in Unit Rates.

**Comment by jbphet** [comment]
I implemented this capability and did a maintenance release of the chains sim to enable testing, and then did a maintenance release unit-rates and created an en_CA (Canadian) translation, see https://phet.colorado.edu/sims/html/unit-rates/latest/unit-rates_en_CA.html.  As far as I can tell, this seems like it works fine for creating a version of the sim with metric units.

In the course of doing this, I realized that the information about what locales can be built is kept in chipper and the locales specified in the build command are verified by comparing against this information.  Since simulations are built with specific versions of chipper, existing simulations will require a maintenance release to support these additional English locales.  This could be a problem for our users, albeit a minor one, because these locales will always show up in Rosetta but won't really be available on all simulations unless they've had a maintenance release that adds the new locales.  I mentioned this to @oliver-phet verbally so that he can keep an eye out for questions from translators about this.  In my opinion, we are going to get so few requests for translations into these new locales that it isn't worth the time and effort to do a maintenance release to make them available to all users.  We can handle such requests - if we ever get any - through specific maintenance releases of individual simulations.

I am assigning this to @ariel-phet to that he is aware of the state of this effort and to make sure that he agrees that a bulk maintenance release isn't warranted.

**Comment by ariel-phet** [comment]
@jbphet agreed bulk maintenance not warranted since this was mainly a special request for Unit Rates. Good that we have this capability going forward if this kind of circumstance arises in future sims. 

Assigning back to @jbphet - feel free to close if nothing else to do here.

**Comment by jbphet** [comment]
Closing.
