### ISSUE TITLE
Add unit to rosetta for translating strings in the mobile apps

### ISSUE THREAD

**Issue by mattpen** [phetsims/rosetta#153]
We should add this before the translatable versions of the app are published so that the initial strings are published in the app versions.

**Comment by mattpen** [comment]
@jbphet - Can we find a time to briefly discuss the best way to do this?

**Comment by mattpen** [comment]
@jbphet and I discussed this today.  We are going to add a new button on the rosetta home page for "Mobile App" translation.  The strings will still be handled by the same backend, by storing them in json files in babel.

**Comment by jbphet** [comment]
Other notes from the discussion:
+ I was actually envisioning a different landing page with two buttons that allows the user to choose between translating a simulation and translating the mobile app.  Choosing a simulation would send the user to the current landing page where they choose a sim and a language.  Choosing the mobile app would land them on a page where they choose only the language, then the mobile strings are presented for translation.
+ A simpler alternative would be to leave the first page the way it is and make the mobile app appear in the list of sims.  I'm not particularly fond of this idea, since it's not really a sim, and I think we'd end up adding a bunch of 'special case' code, but it might be easier if we have limited time and resources to get this done.
+ Rosetta currently looks at published simulations to figure out which strings they use.  We'll need to have some other mechanism, such as simply translating all strings in the English string file for the app(s), to accomplish this.
+ Rosetta kicks off a build when a new translation is submitted.  We'll need to determine if anything like that happens when a new translation of the app strings is submitted.
+ The application will need to be made translatable before much of the work on Rosetta can begin.
+ It would be useful during the development to turn the feature on only for some closely trusted users so that we can do a full test of the translation process.
+ It sounds like this is not needed immediately, and may be at least a month or two out. Given that time frame, I'm going to unassign myself and assign @ariel-phet to schedule it into the larger plan.

**Comment by mattpen** [comment]
> Rosetta kicks off a build when a new translation is submitted. We'll need to determine if anything like that happens when a new translation of the app strings is submitted.

I think we will need to add an interface in the website code that will allow the strings to be stored in postgres via http post request.

**Comment by mattpen** [comment]
> I think we will need to add an interface in the website code that will allow the strings to be stored in postgres via http post request so that they can be made available through the Metadata API.

It might make more sense to build this API into rosetta directly, and it should be cached by varnish.

Another question we'll need to solve is how does rosetta find out what the current english strings are.  The app finds these for sims by parsing them out of the built `_en.html` file.  One option is that we could get them from the strings resource file in the android repo itself, since rosetta presumably already has a Github Oauth token setup (i.e. http request to https://github.com/phetsims/phet-android-app/blob/master/app/src/main/res/values/strings.xml).  

Yet another issue to tackle: there will be small variations in the strings for each version of the app and across platforms.  How do we want to handle requests for different versions of the app?  If the strings are queried at runtime, we'll need to give translators the option to translate any version and any platform.  Perhaps we should build the strings into the apps themselves and do regular (monthly?) releases?  This would mean that translators only need to worry about the latest version for ios and android but would mean greater delays in getting the translations into the apps themselves.

**Comment by mattpen** [comment]
So far I have the new initial screen to choose app or sims working, the screen to choose an app platform/language/version working, and I've populated the android strings on the translate page on ox-dev.  I still have yet to implement saving/submitting.

![image](https://cloud.githubusercontent.com/assets/11747676/26017762/82fb1be6-3728-11e7-89fa-15dedc1faa5b.png)

**Comment by mattpen** [comment]
One more thing we may need to consider is how to setup a testing framework for the strings, so translators can view the context.

**Comment by mattpen** [comment]
String saving and submitting is now working for rosetta for the mobile-apps.  Next up is providing an API for the mobile apps to retrieve the strings at runtime.

**Comment by mattpen** [comment]
We should have a plan for integrating this as part of chipper:2.0 work, although it could be implemented afterwards.

**Comment by mattpen** [comment]
@ariel-phet - are we still planning to add this as part of chipper-2.0?  It would probably be nice to have it up for a few weeks at least before we publish the update for the ios-app.

**Comment by ariel-phet** [comment]
@mattpen yes, I think we would like this as part of finishing off chipper 2.0, but I think registration pages takes precedence.

**Comment by mattpen** [comment]
moving discussion to https://github.com/phetsims/phet-ios-app/issues/315
