### ISSUE TITLE
Translation utility 'Proxy Error'

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#159]
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /translate/sim/projectile-motion/fa.

Reason: Error reading from remote server

**Comment by oliver-phet** [comment]
@mattpen said on 9/6:

> It looks like this is due to part of the rosetta/github interaction failing.  JB and I are looking into it.

**Comment by jbphet** [comment]
I've restarted rosetta and it appears to be working now, and I'll keep an eye on it to make sure that translations are coming in again.

Here is what I found prior to doing the restart: I examined the logs, and it appears that rosetta was somehow getting stuck when trying to submit strings.  There were a number of entries in the log about queuing strings for submission, followed by nothing.  Here's an example from an attempt that I just tried (translating Chains to Abkhazian);
```
Sep 07 16:08:40 phet-server.int.colorado.edu rosetta[65381]: Sep 07 2017 16:08:40 MDT - info: queuing string submission for chains_ab
```

That was the end of the log, i.e. nothing else happened.  Previous successful build entries looked like the one below (this is the last build that worked before the lockup):

```
Sep 03 08:39:44 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 08:39:44 MDT - info: queuing string submission for projectile-motion_sl
Sep 03 08:39:44 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 08:39:44 MDT - info: getting GH client for user jbphet
Sep 03 08:39:44 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 08:39:44 MDT - info: detected multi-line string
Sep 03 08:39:44 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 08:39:44 MDT - info: oldValue = nadgrajen
Sep 03 08:39:44 phet-server.int.colorado.edu rosetta[65381]: od
Sep 03 08:39:44 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 08:39:44 MDT - info: prior to replace operation, oldValue === stringValue = true
Sep 03 08:39:44 phet-server.int.colorado.edu rosetta[65381]: [84B blob data]
Sep 03 08:39:44 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 08:39:44 MDT - info: after the replace operation, oldValue === stringValue = false
Sep 03 08:39:44 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 08:39:44 MDT - info: attempting update for file = projectile-motion/projectile-motion-strings_sl.json
.
.
.
Sep 03 08:39:52 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 08:39:52 MDT - info: finished string submission for projectile-motion_sl
```

It looks like the breakdown occurred during an attempt to create a Hungarian translation of Projectile Motion.  I'm seeing this in the log:

```
Sep 03 11:09:10 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 11:09:10 MDT - info: queuing string submission for unit-rates_hu
Sep 03 11:09:10 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 11:09:10 MDT - info: getting GH client for user jbphet
Sep 03 11:10:17 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 11:10:17 MDT - info: queuing string submission for unit-rates_hu
Sep 03 11:11:38 phet-server.int.colorado.edu rosetta[65381]: Sep 03 2017 11:11:38 MDT - info: queuing string submission for unit-rates_hu
```

It looks like there were three attempts to submit the strings, each about a minute after the previous one.

In addition to keeping an eye on Rosetta to see if translations start coming in again, I'll make a list of all the attempts that failed so that @oliver-phet can let the translators know.  I'll also dig into the code a bit to see if I can learn anything about what caused it to get into a stuck state.

**Comment by oliver-phet** [comment]
@jbphet should I contact translators to let them to to retry?

**Comment by jbphet** [comment]
Here is a list of the submissions that failed (each of these was attempted multiple times):

+ expression-exchange_eu
+ expression-exchange_hu
+ molecule-polarity_hu
+ projectile-motion_es
+ projectile-motion_es_MX
+ projectile-motion_es_PE
+ projectile-motion_fa
+ projectile-motion_hu
+ unit-rates_hu

The locales represented are:

+ es
+ es_MX
+ es_PE
+ eu
+ fa
+ hu

@oliver-phet - that's only six locales, which I think means six translators.  Could you contact those translators and let them know that the system is back up and running (we think), so could they please try again?  Be sure to let them know to try once and if it doesn't appear to work, stop and let us know.

**Comment by jbphet** [comment]
I spent some time reviewing the code, and my best guess is that GitHub was down or having problems and the attempt to get a GitHub client failed, and rosetta doesn't handle this.  If we see this issue again, I could add some additional logging information that explicitly states whether the client was successfully retrieved, since there is no such logging at this time.

The code is not particularly robust to such issues, and the only thing I can think of to do in this case is pass a message all the way back to the user that instructs them to try again later.

For my future reference (or whoever works on this), the method where I suspect the failure occurred is `TranslationUtils.getGhClient`.

**Comment by jbphet** [comment]
I'm leaving this assigned to me and @oliver-phet for now until we can make sure that translations are being successfully submitted again.

**Comment by oliver-phet** [comment]
@jbphet do you have a list of usernames that attempted to submit? We have multiple translator emails for some of those locales.

**Comment by jbphet** [comment]
@oliver-phet  - I'll figure this out and provide them to you in a separate email.

**Comment by oliver-phet** [comment]
I've received confirmation from 1 translator that things are now working.

**Comment by oliver-phet** [comment]
@jbphet Closing this issue for now since it appears to be resolved.
