### ISSUE TITLE
Pass a parameter through to systemctl for offline mode

### ISSUE THREAD

**Issue by zepumph** [phetsims/rosetta#185]
Currently offline mode is decided by a boolean in the top level of the app (`rosetta.js`), but that involved a commit to change the offline status. It would be nice to be able to pass it in as an option when starting rosetta like `sudo systemctl start rosetta --offline`. I'll do some research.

**Comment by mbarlow12** [comment]
I added the `dotenv` package to handle environment variables from a .env file a the project root. Since this isn't checked into git, we can simply set `ENABLED=false` and restart the server (or make a script that handles setting the flag and restarting the server).

It's a little more cumbersome than passing a flag to `systemctl`, but passing command line arguments to `systemctl start` is quite messy.

**Comment by jbphet** [comment]
Approaches for this were discussed at the 12/5/2019 developer meeting, here's what was recorded in the meeting notes:

> @jbphet will try out @samreid's suggestion for command line args above and use it if it works, and will update the documentation accordingly. This will leave sensitive information in the build-local.json. If that doesn’t work, @jbphet will look at pulling the rosetta config information into a separate file and will add the new params there to avoid cluttering the build-local.json file.  If none of these seem to work well, the usage of a .env file will be considered.

I looked into the command line args approach, and decided against because I'd have to change the systemctl service configuration and I have no experience with that, and also because I decided that I preferred having all the configuration handled the same way, i.e. in config file.  In the end, I opted for the 2nd option, where the config information that is specific to rosetta is in a separate configuration file.  This is similar to what is done for the installer builder, as @zepumph pointed out.  So far, this seems to be working out well.

**Comment by jbphet** [comment]
Implemented and verified through the use of the `rosetta-config.json` file.  Closing.
