### ISSUE TITLE
Check how translations are stored on the website database, add credit to all contributing translators

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#194]
How are translation credits being pulled from Github for display on the website translation credit page? https://phet.colorado.edu/en/for-translators/translation-credits/by-locale
It seems that only the user who submitted the translation most recently receives sole credit.

In developer meeting on 7/5 we decided we should be displaying the name and email for *all* users who translated at least one sim string.

**Comment by jbphet** [comment]
I believe the information necessary to list all translators who have contributed for a given sim is available in the DB used by the website, but when we discussed this during today's dev meeting, @mattpen wasn't 100% sure.  I think the next step is to make that determination and, if that information is indeed available, we should move this issue to the website repo and then work with @ariel-phet to determine the priority.

I could be wrong, but I thought the website used to show a list rather than just a single translator (when there was more than one), and I'm pretty sure that's what we decided to do a while back, so there may be some history that can be referenced if and when this is implemented.

**Comment by mattpen** [comment]
@oliver-phet - Is there an example of a sim and locale that should have multiple translators?

**Comment by mattpen** [comment]
@oliver-phet  - Rather, is there an example of a sim/locale that should have multiple translators but does not?

Looks like there may be some sorting issues, but for the two examples I found it is working properly (ABS in es_MX and si)

![image](https://user-images.githubusercontent.com/11747676/42386538-07c0bac4-80fd-11e8-96d1-1714f9452ede.png)

![image](https://user-images.githubusercontent.com/11747676/42386552-0f6ad03e-80fd-11e8-937d-7f0e81ca6aa4.png)

**Comment by oliver-phet** [comment]
Maybe this is working! I was expecting multiple users listed on a single locale line (rather than a locale being repeated for multiple translators).

**Comment by jbphet** [comment]
If it's working, we should just close the issue.  As for the question @mattpen asked:

> @jbphet - Should you be listed as a translator for ABS???

No, and I am on several of the es_MX sims.  I suspect that @DianaTavares did some work on this on a browser instance where I had logged in.  I haven't been worried about it so far, but if it's easy for @mattpen to do, feel free to remove me.  I'll log a separate issue for it.

**Comment by jbphet** [comment]
The issue logged for cleaning up ex_MX credits is https://github.com/phetsims/website/issues/712.
