### ISSUE TITLE
missing Gruntfile and phetLibs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#2]
Rosetta can't be linted because it has no Gruntfile.js, and it's missing phetLibs in package.json.

**Comment by jbphet** [comment]
It's not a sim and doesn't have any dependencies on any PhET libraries, so it doesn't need to have phetLibs.  Adding a grunt file probably makes sense to make the project lintable.

**Comment by pixelzoom** [comment]
I suspect that it will have dependencies on PhET libraries so that Rosetta and sims are both using the same i18n-related utilities (e.g., for code used to validate strings).   So for now, I recommend adding:

> "phetLibs": "rosetta"

**Comment by pixelzoom** [comment]
I made rosetta lintable. Assigning to @jbphet to make sure this doesn't cause any problems.

**Comment by jbphet** [comment]
Linting works, thanks.

There are a number of items in the devDependencies field of package.json that I don't think are really needed, since this isn't a sim and will not be built as such.  However, I'm reluctant to remove them because, I don't know, maybe the grunt tools will freak if the things needed for the other sims around around.  So for now at least, they will be left.

Main issue addressed, closing.

**Comment by pixelzoom** [comment]
@jbphet FYI, I did try paring devDependencies down, but it appears that they are all needed in order to runt the 'lint' task.

**Comment by jbphet** [comment]
That settles it then: they stay.
