### ISSUE TITLE
Common string missing in translation utility [Fractions Suite]

### ISSUE THREAD

**Issue by arouinfar** [phetsims/rosetta#213]
I submitted a `fa` translation of `build-a-fraction` to help out with some app translation testing and ran into an odd situation. 

Compare the `en`, `fa`, and `es` versions of the sim. "Choose your level!" remains untranslated in `fa` because this string is no longer available in the translation utility.
![image](https://user-images.githubusercontent.com/8419308/61422012-f80b6c80-a8c6-11e9-9b79-43c6c5790c84.png)

This should be in the common strings, since @jonathanolson updated [fractions-common-strings_en.json](https://github.com/phetsims/fractions-common/blob/master/fractions-common-strings_en.json) to use Vegas strings in the game, see https://github.com/phetsims/fractions-common/commit/676b835855af65c703c07d1b1f1b928261a2c9ef?diff=unified.

The Spanish translation was submitted not long after 1.0 (early February) before this commit was made. The Farsi translation was submitted last week.

@jonathanolson suggested that I should open an issue in rosetta and co-assign @jbphet.

**Comment by jbphet** [comment]
I dug into this for a while, and I think I know what's going on.  The string "Choose Your Level!" was in fractions-common when the currently live version of this sim was published (v1.0.10).  After publication, @jonathanolson realized that this string already existed in the vegas repo, and changed the code on master to use the vegas string instead, and deleted the redundant string from fractions-common.  However, Rosetta uses master for finding previously translated strings in libraries (an acknowledged weakness, see https://github.com/phetsims/rosetta/issues/219).  Since it can't find the English version of this string in fractions-common (since it's working from the version on master where that string doesn't exist anymore), it doesn't present that string to the user for translation.

This could be fixed by changing the published code to use the vegas version of this string.  I would suggest doing that to solve the problem, since it would be pretty quick, and the issue referenced above it not likely to be addressed any time soon.

@jonathanolson - I think this is a quick fix, and I also think it should be addressed, since any new or updated translations of this sim are likely to run into this issue.  I'll mark it as high-priority to get on your radar, you can adjust as you see fit.

**Comment by oliver-phet** [comment]
Sándor just reported this issue via phethelp. Can he just submit the translation for 'Choose your level' in a sim like Fraction Matcher?

**Comment by jonathanolson** [comment]
I'm not sure. https://github.com/phetsims/QA/issues/463 is pending QA but should presumably help once those are deployed?

**Comment by jbphet** [comment]
I agree that once those changes are deployed Sándor should be able to add the strings for the missing keys via the translation interface and resubmit.  It will be a good test case to make sure that it all worked correctly.

**Comment by muedli** [comment]
Hey, @jonathanolson, @jbphet and I are reviewing issues. Can this be closed?

**Comment by jonathanolson** [comment]
Yes, closing!
