### ISSUE TITLE
verify that Rosetta treats string keys as case-sensitive

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#216]
Over in https://github.com/phetsims/natural-selection/issues/12, I'm considering string file entries that look like this:

``` 
  "F": {
    "value": "F"
  },
  "f": {
    "value": "f"
  },
  "E": {
    "value": "E"
  },
  "e": {
    "value": "e"
  },
  "T": {
    "value": "T"
  },
  "t": {
    "value": "t"
  }
```

Discussing whether case sensitivity is a problem for Rosetta, @jbphet said on Slack:

> I'd suggest that you log an issue to have us test this on Rosetta when you're getting close to publication, and I can figure out a test on ox-dev that could use a dev version of the sim and we could make sure that case sensitivity isn't a problem.

This issue is a pre-requisite to RC testing and publication of Natural Selection. The sim is schedule for publication by 8/1/2020, and RC testing will likely begin around 6/1/2020.  And I'm hoping to accelerate the entire schedule.

Initially assigning to @jbphet.  Feel free to unassigned or mark deferred.

**Comment by pixelzoom** [comment]
I'm using different string keys in natural-selection, so case sensitivity is no longer an issue, see https://github.com/phetsims/natural-selection/issues/12#issuecomment-554599302.   But it would still be good (in general) to know the answer to this question.

**Comment by jbphet** [comment]
I've spent a few minutes thinking about this and looking through the Rosetta code base, and I would say that I'm about 80% confident that string keys that differ only in case would be handled fine by Rosetta.  My reasoning is that, first of all, JavaScript and JSON both are specified as having case-sensitive keys, and Rosetta pulls the keys directly from published sims, which are in JavaScript, and from GitHub, where string files are stored in JSON format, so it doesn't seem like there is anywhere in the extraction process where case information would get lost.  In the repo code there are some usages of `toLowerCase` and `toUpperCase`, but these aren't used on the string keys or values themselves, mostly just for comparisons.

If we want to get 100% certainty on this, we should add some new keys that differ only in case to the "Chains" sim and test translation of these strings.  This would probably take at least a couple of hours, and given @pixelzoom's previous comment, it doesn't seem to me like a good investment of time.  Assigning back to @pixelzoom who can chime in on whether doing "Chains" seems worth it.  He can close or assign to @ariel-phet at his discretion.

**Comment by pixelzoom** [comment]
> Assigning back to @pixelzoom who can chime in on whether doing "Chains" seems worth it. 

Doing the "chains test" seems worth it -- and required, eventually. But if "a couple of hours" is not currently available for doing that test, this doesn't impact my work and the issue can be deferred. As I said in https://github.com/phetsims/rosetta/issues/216#issuecomment-554599377, I've taken a different approach in Natural Selection.  And until this is investigated, I'm generally going to err on the side of caution and assume that Rosetta is _not_ case-sensitive.  

> He can close or assign to @ariel-phet at his discretion.

I don't think that this should be be closed.  It should be left open, to be investigated the next time that a significant chunk of time is carved out to work on Rosetta.

**Comment by jbphet** [comment]
@pixelzoom - We are doing some cleanup of the issues in the rosetta repo and came across this one.  Does the fact that Natural Selection has been successfully published and translated into a number of locales indicate that this is a non-problem and can be closed?

**Comment by pixelzoom** [comment]
> Does the fact that Natural Selection has been successfully published and translated into a number of locales indicate that this is a non-problem and can be closed?

No - I don't think we can draw that conclusion from Natural Selection.  Searching the string files in babel, I can't find any cases where the translator changed the strings shown in https://github.com/phetsims/rosetta/issues/216#issue-521231272.

Why not just test this in Rosetta?

**Comment by jbphet** [comment]
I wanted to come up with a reasonably quick way to test this without having to modify and rebuild Chains, so here's what I did:

- I manually modified the `english-string-map` file for natural-selection on ox-dev to use the keys "F" and "f" instead of "furDominant" and "furRecessive" (respectively) and used "E" and "e" for "earsDominant" and "earsRecessive".
- I modified the Rosetta code locally to spit out the string keys and values.
- I ran Rosetta locally and loaded natural-selection for the ab locale.

Note that none of these changes were committed, this was purely an attempt to verify that the keys are case sensitive.

Based on the results of the test, the keys are clearly case sensitive.  Here is what was shown on the translation page:

![image](https://github.com/phetsims/rosetta/assets/3082831/37e75aa7-eb63-4ebe-b308-75b332699d66)

And here is what was logged to the console (apologies for the embedding marks, but that's how we set them all up in Rosetta to display correctly to all users):

![image](https://github.com/phetsims/rosetta/assets/3082831/25e19bca-d67d-46e5-a0cc-a205d40e28bd)

I think this is sufficient proof, so I'm going to close.  @pixelzoom - if you see this go by and have objections, reopen.
