### ISSUE TITLE
Show donate query parameter ends up in our route

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/rosetta#249]
@jbphet and I noticed that the query parameter that shows the donation popup can end up in our route, e.g. phet.colorado.edu/translate/?showDonate... and this basically breaks Rosetta.

**Comment by jbphet** [comment]
I feel like this has come up before, but I don't recall the context, but I think I discussed it with @mattpen and he may have changed something.  @mattpen - do you know anything about this, and does something need to change on phet-server and/or phet-dev-server to make it go away?

**Comment by mattpen** [comment]
This did come up before for the profile update ask.  That change didn't get applied to the donation ask, because it didn't exist yet.  I refactored the path checking so that all modal dialogs use the same logic for verifying if the path is valid for receiving these query parameters.  This will require a deploy of the tomcat application.

**Comment by liam-mulhall** [comment]
@mattpen, is this deployed? I haven't seen this in a while.

**Comment by mattpen** [comment]
Yes, this would have been deployed around the end of December.
