### ISSUE TITLE
Add documentation about changing common code string keys on master

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#260]
On 4/9/2020 in https://github.com/phetsims/scenery-phet/issues/570#issuecomment-611681781:
> Dev meeting decision: @jbphet will add documentation about this to Rosetta.

Since that was 10 months ago, I'm moving this documentation task from scenery-phet to rosetta, and closing the scenery-phet issue. 

I really don't understand https://github.com/phetsims/scenery-phet/issues/570, so if @jbphet has questions, he should consult with @zepumph.

**Comment by zepumph** [comment]
I changed the name. The PSA came out of a specific case, but it demonstrated a general constraint of Rosetta and i18n strings in our project. For common code, we always take the string values from master. Thus each version of each sim doesn't have its own, branched set of strings for scenery-phet. This makes sense when thinking about reusing the same translations between multiple sim versions, because common code string keys don't change often, but it means that changing string keys on master can break older translations. This will only get more challenging as we add more description strings to common code. Thus having documentation was at least a first step in tackling this confusion.

**Comment by jbphet** [comment]
There is documentation that already exists for this.  @zepumph - Could you take a look at what exists and let me know if it is lacking in some way and, if so, what improvements you would suggest?  Please see 
https://github.com/phetsims/rosetta/blob/master/doc/how-to-change-a-string-key.md#changing-a-string-key-for-a-common-code-repository

**Comment by zepumph** [comment]
That is excellent from my perspective. Thanks!
