### ISSUE TITLE
Missing fa CCK:AC translations

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#275]
A Persian (fa) translator just wrote in that they have translated both AC sims but neither has been published to the site. Both sims have [string files](https://github.com/phetsims/babel/tree/master/circuit-construction-kit-ac)

Assigning @liam-mulhall and @jbphet

**Comment by jbphet** [comment]
I can see two build error notifications in my email inbox, and one of the lines says, "Error: Cannot find module 'acorn'".  That means that the problem is likely caused by the problems that we've been having lately with builds due to the recently introduced dependency on this module, see https://github.com/phetsims/perennial/issues/256.

**Comment by jbphet** [comment]
@oliver-phet - I was able to publish these translations by triggering a rebuild, so the immediate problem is resolved and you can let the translator know that Persian translations of CCK-AC and CCK-AC-virtual-lab are now available on the site.

For what it's worth, we are working on the issue that caused this in the first place, but it's not fully resolved yet, so it is possible that this could come up again for other translators.  If it does, just log an issue like this, and @liam-mulhall or I will take care of it.  Hopefully we'll have the root cause corrected soon.

**Comment by oliver-phet** [comment]
Thanks, @jbphet. Translator notified!
