### ISSUE TITLE
The trigger-build route is working but not returning a decent response

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#276]
In https://github.com/phetsims/rosetta/issues/161 we added a URL (aka a "route" in ExpressJS terms) to trigger builds of translations without adding ourselves as translators to the credits.  I just used it while working to address some reports of missing translations (see https://github.com/phetsims/rosetta/issues/275), and according to the build server log, it worked, but in the web browser we got the following screen:

![image](https://user-images.githubusercontent.com/3082831/148847338-d6490d4f-069a-400a-bf07-ef830c62b0b9.png)

I'm pretty sure that this used to return a crude but clear screen that the request had been processed.  I'm not sure when or how this got broken, but it should be fixed.

@liam-mulhall is working on a pretty big refactor, so we can wait to address this until that is published if he feels like that's the best approach.

**Comment by liam-mulhall** [comment]
@oliver-phet was having issues using the trigger build route, so I worked on this a bit. @mattpen helped me diagnose the issue. (Thanks, Matt!) Not sure where this issue crept in. I believe this issue is fixed in https://github.com/phetsims/rosetta/commit/4f52e00963b8d4b5cd6c97e08a2f970b2ee0b691.

I tested locally and I was able to see the old "success" message:

![fix](https://user-images.githubusercontent.com/60749003/150004711-6c140aa5-03c1-4060-918b-4e4e90caeb0e.png)

The build server logs seem to indicate the build went through:

```
Jan 18 11:57:36 phet-server.int.colorado.edu build-server[30296]: info: deploy request received, original URL = http://phet.colorado.edu/deploy-html-simulation
Jan 18 11:57:36 phet-server.int.colorado.edu build-server[30296]: simName:"acid-base-solutions"
Jan 18 11:57:36 phet-server.int.colorado.edu build-server[30296]: version:"1.2.26"
Jan 18 11:57:36 phet-server.int.colorado.edu build-server[30296]: locales:["es"]
```

(I tested by changing a character from lowercase to uppercase in es/acid-base-solutions. I'll have to change it back.)

I could deploy these changes, but phet-server's SHA is d37d0da36df42a81cb5dc2020425c12342261af4, which is back quite a few commits. It wouldn't be prudent to deploy without testing. I don't want to sink too much more time into this issue since I'm trying to finish the refactor. @jbphet, what are your thoughts on deploying? I'd rather keep the version that's running in place since we know that version is working reasonably well. If you or ON need to trigger a build, I'd be happy to do so on my machine with this fix in place.

**Comment by jbphet** [comment]
@liam-mulhall asked:

> @jbphet, what are your thoughts on deploying? I'd rather keep the version that's running in place since we know that version is working reasonably well. If you or ON need to trigger a build, I'd be happy to do so on my machine with this fix in place.

I'm okay with waiting until the refactor is completed and redeployed, then testing a trigger-build operation and verifying that we get a good response.  It seems wise to leave it in a stable-but-mildly-broken state verses risking a fix that could end up costing us time.  Assigning back to @liam-mulhall for follow-up once the refactored version is live.

**Comment by liam-mulhall** [comment]
I've used the trigger build route pretty extensively since we updated phet-server's Rosetta (the changes in https://github.com/phetsims/rosetta/commit/4f52e00963b8d4b5cd6c97e08a2f970b2ee0b691 have been working). Closing.
