### ISSUE TITLE
Improve look of the current prototype pages

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#3]
The prototype pages are incredibly basic at this point.  It would be good to add some PhET styling, similar to what was done for the sonification page, which can be seen here: http://www.colorado.edu/physics/phet/dev/sonification/sonification-links.html.  For now, it is okay for the translation code to directly access the CSS file at the web site, though eventually we may want to separate the two.

In case the sonification page is ever removed, I've captured a screen shot of it below.

![sonification](https://cloud.githubusercontent.com/assets/3082831/6559614/c718e40e-c649-11e4-9794-c7d4eaedb25b.png)

**Comment by aaronsamuel137** [comment]
Assigning to @BrianNewsom. We can go over some more details next time we pair program if you'd like.

**Comment by aaronsamuel137** [comment]
@BrianNewsom, we decided that we are going to have the css in rosetta completely separate from the website repo. Feel free to pull images from the main website though (i.e. link to phet.colorado.edu instead of copying the image files into rosetta).

In addition, you don't need to match the top banner with the main website, just make it look sort of similar, and also smaller. No need to keep the search bar either.

Let me know if you have questions.

**Comment by BrianNewsom** [comment]
@aaronsamuel137 I've got something up - a lot is just taken from sonification and then a few simple additions.  I added the user up in the bar at the top - I'm not really happy with it but I think if done well it could be nice.  Let me know what you'd like to see done differently! Thanks.

**Comment by aaronsamuel137** [comment]
Closing
