### ISSUE TITLE
Change copy English value icon?

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#334]
@oliver-phet, @DianaTavares, what do you think a better icon would be for the copy English value icon? I am using https://icons.getbootstrap.com/.

In the test for Rosetta 2.0 (https://github.com/phetsims/qa/issues/869), @DianaTavares noted that it would be helpful to have a button to copy the English value to the clipboard so that it could be easily pasted into Google Translate.

I think this could be done with the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) easily enough. And we could add this feature in a future release.

However, the current button has an icon that looks a lot like a button for copying to the clipboard:

![image](https://user-images.githubusercontent.com/60749003/208786176-acecb4cb-e700-4285-ba6f-5c98b9bee47c.png)

We should probably change this icon *before* Rosetta 2.0 is released to avoid confusion with a future copy to clipboard button.

**Comment by DianaTavares** [comment]
I like the two pages icon for copy in the clipboard. What about an arrow to represent passing the English string to the translation side? 
![image](https://user-images.githubusercontent.com/26031501/208788052-e5d9646d-07f1-46f3-9fc8-3883e296be00.png)

![image](https://user-images.githubusercontent.com/26031501/208788079-1bdf5723-fa15-47e8-8788-478ebbe1d755.png)

**Comment by oliver-phet** [comment]
Sure, probably not a bad call to better distinguish this behavior from 'copy to clipboard'.
I actually like [box-arrow-in-right](https://icons.getbootstrap.com/icons/box-arrow-in-right/) because I think it better implies inserting something in the box (the English string).

I'd like to defer any copy to clipboard until after 2.0, though. I remember @kathy-phet had some reservations around allowing translators to copy the value of English strings.

**Comment by Nancy-Salpepi** [comment]
In round 2: copy button has been changed to box-arrow-in-right. 

Closing.
