### ISSUE TITLE
Distorted chemical symbols for right-to-left languages 

### ISSUE THREAD

**Issue by solaolateju** [phetsims/rosetta#352]
Sim: Build a molucule
Locale: Arabic_Morocco (ar_MA)

Hi Liam,

We have a complaint (from a translator) for the formatting of chemical symbols for his locale.   
The symbols are rendered right-to-left in one instance but unchanged in another within the same line. 
The chemical symbols should keep the standard form. Is it possible to have the affected stings remain unchanged?
![image](https://user-images.githubusercontent.com/18397749/211787463-d8d86ed2-5484-4a5e-82e8-454b916ddc5e.png)

**Comment by liammulh** [comment]
I believe this is the same issue as described in https://github.com/phetsims/build-a-molecule/issues/220. I think the status of that issue is that we have an idea of how to fix it, but the people working on it (mostly JO and JB) are busy and it might not be fixed soon.

I'm going to close this issue as a duplicate.
