### ISSUE TITLE
Discuss long strings with sim designers and developers

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#364]
In https://github.com/phetsims/rosetta/issues/349, we noticed that there can be really long strings available for translation.

- Rosetta was not designed to handle string keys whose values are long paragraphs of text.
- Rosetta was designed to handle string keys whose values are single words.

## Questions that should be addressed

1. Should we do anything about existing long strings other than make the translation field a textarea instead of an input?
2. How can we design sims so that the translation utility doesn't get paragraphs of text for a single string key?

**Comment by liammulh** [comment]
Similar issue: https://github.com/phetsims/rosetta/issues/314.

**Comment by jbphet** [comment]
Discussed in the 6/14/2023 review meeting and we'd like to make it so that the text area can be dragged a bit to the right in addition to dragging down.  Once that's done, this issue can be closed.  @kathy-phet suggests working with @chrisklus on this.

**Comment by terracoda** [comment]
I slacked members of the Global Team about this Bengali translation I found. I found it on the Overview Tab of the Preferences Menu in Greenhouse Effect.
<img width="1068" alt="Screen Shot 2023-06-16 at 3 01 46 PM" src="https://github.com/phetsims/rosetta/assets/1902116/410be0b8-edfe-4337-b7a6-0127f8e15038">

Maybe it is a translation in process. Not sure. The English is placed in parentheses, so it looks intentional.

It is a long string, so maybe it is related to this issue.

**Comment by terracoda** [comment]
A member of the global team will contact the translator, so the above comment should get resolved.

**Comment by jbphet** [comment]
The ability to enlarge the text area where the new strings are entered has now been added and deployed on both ox-dev and phet-server2.  Screenshot of extended areas:

![image](https://github.com/phetsims/rosetta/assets/3082831/07e55504-b75f-4d26-a9c3-126c59c2fbdd)

The work for this is now complete, closing.
