### ISSUE TITLE
Handling truly empty strings

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#388]
I didn't even know a string like this existed:
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/5090275/224825466-943b0c32-b082-4e05-a559-3dea613ef70f.png">

There are 2 of these in Molecule Shapes that prevent a translator from "fully" translating the sim:
```
geometry.empty
shape.empty
```

@liammulh do you have thoughts on better handling empty strings like this?

**Comment by liammulh** [comment]
I don't think there is a point to presenting these strings to the translators. Here is how they look in the published sim:

```
    "MOLECULE_SHAPES/geometry.empty": "",
    "MOLECULE_SHAPES/shape.empty": "",
```

**Comment by liammulh** [comment]
Patch added in https://github.com/phetsims/rosetta/commit/a408ed7128e428b29e3cab6224f969876dceac94.

**Comment by liammulh** [comment]
I deployed this fix, and I am no longer seeing `geometry.empty` and `shape.empty`.

**Comment by oliver-phet** [comment]
I'm not seeing those strings either. Do you know if/when the statistics will update?
<img width="882" alt="image" src="https://user-images.githubusercontent.com/5090275/225433271-78670f20-cb48-46ee-af3a-4253c6206df1.png">

**Comment by jbphet** [comment]
@jonathanolson - The string keys `geometry.empty` and `shape.empty` in `molecule-shapes-strings_en.json` are causing some issues for translators.  In the English string file, they are both empty strings, and with the new implementation of Rosetta the translators don't get a 100% on their translation unless they provide a value, which may be inappropriate.  Also, a number of translators previously supplied values for these strings (well before Rosetta 2.0 was released), and they provided strings that appear to match the key rather than the value.

Do we really need to have these strings available for translation at all?  If so, why?

**Comment by jonathanolson** [comment]
I thought that translators could provide a translation if desired. @arouinfar thoughts on this?

Also, it looks like we're not generating entries in MoleculeShapesStrings.ts for these, so the sim will fail when ported to TS. It's possible to just hardcode empty strings in those cases.

**Comment by jbphet** [comment]
@arouinfar - It sounds like @jonathanolson is okay with the idea of just changing these to hardcoded empty strings.  This would help both the translation system and the port to TS.  Any objections?

I'm raising the priority on this, since we'd like to get it resolved fairly quickly and I think a quick call could be made.

**Comment by arouinfar** [comment]
> @arouinfar - It sounds like @jonathanolson is okay with the idea of just changing these to hardcoded empty strings. This would help both the translation system and the port to TS. Any objections?

No objections here!

**Comment by jonathanolson** [comment]
Removed the strings in the commit above. Due to TinyForwardingProperty, I had to instrument the empty string Properties (global.model.emptyElectronGeometryStringProperty / global.model.emptyMoleculeGeometryStringProperty). @arouinfar is that acceptable?

**Comment by arouinfar** [comment]
> Due to TinyForwardingProperty, I had to instrument the empty string Properties (global.model.emptyElectronGeometryStringProperty / global.model.emptyMoleculeGeometryStringProperty). @arouinfar is that acceptable?

Yes, that sounds acceptable to me.

**Comment by jbphet** [comment]
For reference, here is what these strings look like when presented to the user in the translation utility (Rosetta).  This is a portion of the Polish translation page for the full Molecule Shapes sim.

![image](https://user-images.githubusercontent.com/3082831/235763682-8b882a3f-05a9-428b-adc8-2af72530d46c.png)

**Comment by jbphet** [comment]
The Molecule Shapes sims have been redeployed and the `.empty` strings no longer appear and the stats are now at 100% for the Polish translations.  @oliver-phet - Are we good to go here?  So you want to let the translators know?

**Comment by oliver-phet** [comment]
Sweet! I'll let the Polish translator who originally reported know things are fixed.
