### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#4]
As of this writing, the translation utility logs a fair amount of debug information using console.log.  This should be replaced with a logging system.  Unless anyone objects, I'm thinking we should use the same logging system that is being used for the port of the installer-builder code, which is called "winston" and can be found here: https://www.npmjs.com/package/winston.  Examples of its usage can be seen in the installer-builder repo here: https://github.com/phetsims/installer-builder.

For now, whoever works on this should use their best judgement as to what is logged as info versus warnings versus errors - we can always go back and refine this later.

**Comment by BrianNewsom** [comment]
I'm not sure if it's a permissions issue or if the link is broken, but I don't see anything at https://github.com/phetsims/installer-builder.

**Comment by aaronsamuel137** [comment]
It's a private repo, I've just given you permissions.

**Comment by BrianNewsom** [comment]
I took a first stab at this.  The file structure didn't quite resemble that of installer-builder so I had to handle things a little differently.  Instead of passing the requirements around, this app just requires everything used, so I created a Winston logger factory that is imported in each major file requiring logging.  If this is bad practice or hard to maintain (which I could see depending upon the size of this project) I will happily explore an alternative.  It does add the benefit of logging to different files from different pieces though, which could be useful.

Anyways, let me know what you think, @aaronsamuel137 and @jbphet,  I'd love feedback/criticisms.

**Comment by aaronsamuel137** [comment]
Looks pretty good. A few comments:

#### 1.

I think it would be better to explore an alternative to the factory approach you are using. It seems odd to have 

```js
var winston = require( __dirname + '/js/logger' )( );
```

as a module import, since the rest of the imports are not function calls like this, and it is not consistent with the import convention of:

```js
    var winston = require( 'winston' );
```

Would it be possible to follow a pattern more similar to the installer build? I haven't looked into it too closely, so I'm not sure what complications would be involved.

#### 2.

This is a minor point, but thought I would mention it just so you are aware. There is no need to use vars here, since you are just redefining the parameter variables:

```js
    var logFile = logFile || defaultLogFile;
    var silent = silent || defaultSilent;
```

#### 3.

We have a PhET code formatter that I forgot to tell you about. Import joist/util/phet-idea-codestyle.xml into IntelliJ and then use the automatic formatter to get the code consistent with the PhET format. Also, take a look at our style guidelines here: https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit?pli=1#heading=h.1oxr3ptyo50w (a lot of this applies mostly to sim development, but it's good that you at least get an idea)

**Comment by aaronsamuel137** [comment]
Assigning to @BrianNewsom

**Comment by BrianNewsom** [comment]
@aaronsamuel137 added logging with winston & parsing of command line arguments.  A lot of it is straight out of installer builder.  Let me know what you'd like to see done differently.

**Comment by aaronsamuel137** [comment]
Looks great, thanks! Closing

**Comment by aaronsamuel137** [comment]
@BrianNewsom - one thing I didn't catch before. If you are adding a new module like winston, be sure to add it to the package.json file so that it is automatically installed with ```npm install```. See my last commit: cf37d3d1c212a17a0ee37e6e371b2567c9290467

**Comment by BrianNewsom** [comment]
@aaronsamuel137  - Shoot, sorry! I knew that, apparently Winston somehow slipped through the cracks, i added the rest.  Appreciate it!
