### ISSUE TITLE
Strings (voicing?) missing from Rosetta

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#420]
A longtime translator wrote in that both Quadrilateral and Calculus Grapher appear to be missing some strings (the utility is reporting 75% and 77% completion, respectively) even though all strings have been translated in the utility.

The translator suspects there are some voicing strings that aren't available for translation but are being counted for translation completeness:
![Screenshot_20230621_111854](https://github.com/phetsims/rosetta/assets/5090275/4c0762d0-7842-4fa1-a8cd-1868e96beb2f)

I _think_ Rosetta is counting Quadrilateral Voicing strings towards the statistics, but the strings aren't actually available to be translated? But I'm not sure if that's a Rosetta or a Quadrilateral problem.

I'm not sure what might be causing the count issue in Calculus Grapher - it appears to be fully translated?

This will probably need @jbphet to investigate/confirm?

**Comment by jbphet** [comment]
I'm taking a quick look at this because it has been on my backlog for a while.  I loaded the currently live version of the sim (v 1.1.5), and I see this in the preferences dialog "Audio" section:

![image](https://github.com/phetsims/rosetta/assets/3082831/b27e6c46-1b83-40d8-ac85-80410ce436d4)

In the same section of the dialog in the zh_TW translation, I see this, which seems to indicate that the voicing strings are no longer shown on non-English sims:

![image](https://github.com/phetsims/rosetta/assets/3082831/e1f246e5-e196-4188-938f-4bf23275e583)

Also, the live translation utility is showing that 100% of the strings are translated for Quadrilateral.  Here's a screen capture:

![image](https://github.com/phetsims/rosetta/assets/3082831/52edae00-5cd5-43a3-a2f7-1d50c1abf941)

@oliver-phet - The information above would seem to indicate that this issue has been resolved, though I myself didn't do any work on it.  My guess is that @jessegreenberg and possibly @liammulh realized the problem and fixed it.  Are you okay to close?

**Comment by oliver-phet** [comment]
@jbphet I just investigated a bit and I agree, I think this has been fixed. The reason those sims show 100% translation completion is because the voicing strings are actually available to translate (they weren't available before and counted against "completion"):
<img width="1507" alt="image" src="https://github.com/phetsims/rosetta/assets/5090275/f9c805fa-281e-440c-ad4c-7e5100ed2373">

I'm not sure this is the best way to fix this problem (it leads to a lot of unused translation work). If you think it's fine to have translators continue to translated these strings, this can probably be closed.

**Comment by jbphet** [comment]
Thanks @oliver-phet - that's a good observation.  @jessegreenberg - What would be your opinion on this - should I modify Rosetta such that the voicing strings are no longer available for translation and are not counted as part of the total?  Or shall I just leave them there, unused as they are, in case the feature becomes available in multiple languages at some point?

**Comment by oliver-phet** [comment]
Ah thanks for that additional info @jessegreenberg - the voicing strings available in the utility are intended to be translated, so I think this issue can be closed!
