### ISSUE TITLE
Sorting by translated strings breaks page

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#429]
Attempting to sort by 'Translating Strings' causes an error that continues to popup (maybe 7-10 times)
<img width="751" alt="image" src="https://github.com/phetsims/rosetta/assets/5090275/9f42846b-cda5-4081-a765-029cf8f12bc6">

Possibly caused by a sim having over 100% strings?

**Comment by jbphet** [comment]
I started off by trying to duplicate this on the live version of the translation utility.  I was able to duplicate the problem on https://phet.colorado.edu/translate/da (Danish) and https://phet.colorado.edu/translate/fr (French), but https://phet.colorado.edu/translate/es (Spanish) worked just fine.

Here is a screenshot of the problem occurring on the French translation report screen:

![image](https://github.com/user-attachments/assets/aa476cb6-42c5-4af3-be5f-25777ea18a19)

I then duplicated it on my local machine, and found that the problem was that `null` values were being set for some of the percentages in the translation report object, and this was causing problems when trying to sort those objects.  I'm not sure what the `null` values are supposed to represent, but I noticed that some of the code that was supposed to be calculating the percentage value of a translation was not correctly handling the case where there were zero strings.  I changed this, and the problem went away.  I don't feel great about this fix, since I don't feel like I fully understand it, but I think it is worth deploying to see if it at least resolves the problem.

**Comment by jbphet** [comment]
@oliver-phet - I've made some changes that I think may address the problem that you described in the opening comment.  I had found some ways to duplicate it, and they no longer occur.  I'm not sure exactly how you were creating this, so can you test on the live version and see if the problem is gone?

**Comment by oliver-phet** [comment]
@jbphet I did a bit of testing using a few locales and can't reproduce the original issue either. I'd say we close for now and I'll reopen if I hear from any translators (or I experience myself).

**Comment by jbphet** [comment]
Post closure note: I wanted to double check that the translation system was working end-to-end after making these changes, so I just examined the Rosetta logs as well as the available simulations on the main website that have been submitted since the changes went live.  I can see several successful submissions, including ones for mean-share-and-balance in Italian, Brazilian Portuguese, and Swahili.  This helps to increase my confidence that this didn't introduce any dire regressions.
