### ISSUE TITLE
Should session be checked on every page serve?

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#80]
There is a comment in routes.js that says:

```js
/*
 .
 .
 .
 * TODO: As of mid-Feb 2015, this checks the session on every page serve.  It would probably be better to do some local
 * management of sessions, and only re-check them periodically.
 .
 .
 .
 */
```

I believe I wrote this comment originally, and did so because I was concerned that checking session status for every page might make the translation utility operate a little slowly.  @aaronsamuel137 probably has a better feel for whether this is true, since he's been doing the bulk of the development and testing on this.  We should either remove this comment, add some local session management, or create a new issue about adding local session management and mark it with the "not for 1.0" label.  I'll leave it to @aaronsamuel137's discretion as to which option makes the most sense.

**Comment by aaronsamuel137** [comment]
I've updated the docs here. Basically, I don't think there is a need to address this. The current behavior is for rosetta to check for a session on the main website. If a session is found and the user is a trusted translator, that information is stored in a session created by rosetta, so that future calls to checkForValidSession are just a simple if statement, and don't need to call back to the main website every time.

Assigning to @jbphet for review.

**Comment by jbphet** [comment]
The update to the comments looks good, and I agree that this should fully address the issue.  Closing.
